[fix]fix：Clean up redundant code
akamai/AkamaiOPEN-edgegrid-golang pull request #178
Opened 2023-01-09 10:11 UTC by LhdDream

Conflict on lines 198 and 206 of /pkg/edgegrid/config.go

In line 198, we have set MaxBody to 0

And we are on line 205, we judge whether MaxBody is less than 0

I think line 198 is redundant, which will invalidate the judgment of line 205, and force MaxBody to MaxBodySize

![image](https://user-images.githubusercontent.com/33065391/211284686-b445225b-fa9f-473a-bdcb-a2fceeee678e.png)

2023-01-13 13:41 UTC, kaush- commented
HI @LhdDream,Can you please

2023-01-13 13:43 UTC, kaush- requested changes
Squash commits

2023-01-14 14:48 UTC, LhdDream commented
ok

2023-01-14 15:31 UTC, LhdDream commented
Already Squash commits, please re-do the code review @kaush-

2023-03-13 11:57 UTC, mimazaka approved these changes

2023-03-13 12:04 UTC, kaush- approved these changes

2023-03-13 12:11 UTC, merged